# Cloud Build configuration for Frontend
steps:
  # Build the Docker image with build arguments
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/garage-door-frontend:$COMMIT_SHA',
      '--build-arg', 'VITE_API_BASE_URL=${_API_BASE_URL}',
      '--build-arg', 'PUBLIC_API_BASE_URL=${_API_BASE_URL}',
      '.'
    ]

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/garage-door-frontend:$COMMIT_SHA']

# Substitutions for build arguments
substitutions:
  _API_BASE_URL: 'https://garage-door-backend-${PROJECT_NUMBER}.${_REGION}.run.app/api'
  _REGION: 'us-central1'

# Store the image in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/garage-door-frontend:$COMMIT_SHA'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY

# Timeout
timeout: '1200s'
